#-----------------------------------------------------------------------
# Copyright IONA Technologies 2002-2005. All rights reserved.
# This software is provided "as is".
#-----------------------------------------------------------------------


#--------
# Uncomment one of the following lines, depending on which
# CORBA product you are using.
#--------

!include "Makefile.win.inc.orbix"
#!include "Makefile.win.inc.orbacus"
#!include "Makefile.win.inc.tao"
#!include "Makefile.win.inc.omniorb"
