#-----------------------------------------------------------------------
# Copyright IONA Technologies 2002-2005. All rights reserved.
# This software is provided "as is".
#-----------------------------------------------------------------------

!include "..\..\Makefile.win.inc"

#--------
# Lists of files used by make rules.
#--------
OBJ =		PoaUtility.obj

#--------
# Rules
#--------

default:	all

all:		$(OBJ)

clean:
	-del *.obj *.pdb
